version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.6.0
        command: launch manager
        environment:
        - CALIPER_BIND_SUT=fabric:fabric-gateway
        - CALIPER_BENCHCONFIG=caliper/benchmarks/benchmark-config.yaml
        - CALIPER_NETWORKCONFIG=caliper/networks/networkConfig.yaml
        volumes:
        - ~/scdt-exp/fabric-samples:/hyperledger/caliper/workspace


