# Dockerfile.util
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY ../package*.json ./
RUN npm install
RUN npm install @node-wot/core
RUN npm install @node-wot/binding-http
RUN npm install abort-controller


# App source
COPY util.js .

# Expose the port util server will run on
EXPOSE 6000

# Run the util.js
CMD [ "node", "util.js" ]
