version: '3.9'

services:
  wotgateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
  
  utilserver:
    build:
      context: .
      dockerfile: Dockerfile.util
    ports:
      - "5000:5000"
    depends_on:
      - wotgateway
    environment:
      - WOT_GATEWAY_URL=http://wotgateway:8080/mylamp
