# Dockerfile.gateway
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY ../package*.json ./
RUN npm install
RUN npm install @node-wot/core
RUN npm install @node-wot/binding-http

# App source
COPY WoTgateway.js .

# Expose the port WoTgateway will run on
EXPOSE 8080

# Run the WoTgateway.js
CMD [ "node", "WoTgateway.js" ]
